# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyxpad_main.ui'
#
# Created: Fri Mar  1 22:40:35 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 659)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.sourceTab = QtGui.QWidget()
        self.sourceTab.setObjectName("sourceTab")
        self.gridLayout_6 = QtGui.QGridLayout(self.sourceTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.sourceTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.sourceTab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.readDataButton = QtGui.QPushButton(self.sourceTab)
        self.readDataButton.setObjectName("readDataButton")
        self.gridLayout.addWidget(self.readDataButton, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.sourceTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.sourceTab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 4, 1, 1)
        self.sourceDescription = QtGui.QCheckBox(self.sourceTab)
        self.sourceDescription.setObjectName("sourceDescription")
        self.gridLayout.addWidget(self.sourceDescription, 0, 5, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.sourceTable = QtGui.QTableWidget(self.sourceTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceTable.sizePolicy().hasHeightForWidth())
        self.sourceTable.setSizePolicy(sizePolicy)
        self.sourceTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.sourceTable.setAlternatingRowColors(True)
        self.sourceTable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.sourceTable.setShowGrid(False)
        self.sourceTable.setColumnCount(1)
        self.sourceTable.setObjectName("sourceTable")
        self.sourceTable.setColumnCount(1)
        self.sourceTable.setRowCount(0)
        self.sourceTable.horizontalHeader().setVisible(False)
        self.sourceTable.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.sourceTable, 1, 1, 1, 1)
        self.treeView = QtGui.QTreeWidget(self.sourceTab)
        self.treeView.setColumnCount(2)
        self.treeView.setObjectName("treeView")
        self.treeView.headerItem().setText(0, "1")
        self.treeView.headerItem().setText(1, "2")
        self.gridLayout_3.addWidget(self.treeView, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.sourceTab, "")
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.gridLayout_5 = QtGui.QGridLayout(self.dataTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_2 = QtGui.QSplitter(self.dataTab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.dataTable = QtGui.QTableWidget(self.splitter_2)
        self.dataTable.setAlternatingRowColors(True)
        self.dataTable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.dataTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dataTable.setShowGrid(False)
        self.dataTable.setGridStyle(QtCore.Qt.SolidLine)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(4)
        self.dataTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.textOutput = QtGui.QTextEdit(self.splitter_2)
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName("textOutput")
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.commandInput = QtGui.QLineEdit(self.layoutWidget)
        self.commandInput.setObjectName("commandInput")
        self.gridLayout_4.addWidget(self.commandInput, 0, 1, 1, 1)
        self.commandButton = QtGui.QPushButton(self.layoutWidget)
        self.commandButton.setObjectName("commandButton")
        self.gridLayout_4.addWidget(self.commandButton, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dataTab, "")
        self.plotTab = QtGui.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.tabWidget.addTab(self.plotTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdd_source = QtGui.QMenu(self.menuFile)
        self.menuAdd_source.setObjectName("menuAdd_source")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_config = QtGui.QAction(MainWindow)
        self.actionLoad_config.setObjectName("actionLoad_config")
        self.actionSave_config = QtGui.QAction(MainWindow)
        self.actionSave_config.setObjectName("actionSave_config")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionXPAD_tree = QtGui.QAction(MainWindow)
        self.actionXPAD_tree.setObjectName("actionXPAD_tree")
        self.actionNetCDF_file = QtGui.QAction(MainWindow)
        self.actionNetCDF_file.setObjectName("actionNetCDF_file")
        self.menuAdd_source.addAction(self.actionNetCDF_file)
        self.menuAdd_source.addAction(self.actionXPAD_tree)
        self.menuFile.addAction(self.menuAdd_source.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_config)
        self.menuFile.addAction(self.actionSave_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyXpad", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.readDataButton.setText(QtGui.QApplication.translate("MainWindow", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Trace:", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceDescription.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceTable.setToolTip(QtGui.QApplication.translate("MainWindow", "List of available signals", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sourceTab), QtGui.QApplication.translate("MainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.commandButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdd_source.setTitle(QtGui.QApplication.translate("MainWindow", "Add source", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_config.setText(QtGui.QApplication.translate("MainWindow", "Load config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_config.setText(QtGui.QApplication.translate("MainWindow", "Save config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setToolTip(QtGui.QApplication.translate("MainWindow", "Exit pyXpad", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXPAD_tree.setText(QtGui.QApplication.translate("MainWindow", "XPAD tree", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNetCDF_file.setText(QtGui.QApplication.translate("MainWindow", "NetCDF file", None, QtGui.QApplication.UnicodeUTF8))

