# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyxpad_main.ui'
#
# Created: Fri Oct  7 15:25:29 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

# Hand-edited to make it work with Qt4 & Qt5
from Qt import QtCore, __qt_version__
from Qt.QtWidgets import *

if __qt_version__.split('.')[0] == '5':
    UnicodeUTF8 = 0
else:
    UnicodeUTF8 = QApplication.UnicodeUTF8
# end of hand-edits

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 659)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.sourceTab = QWidget()
        self.sourceTab.setObjectName("sourceTab")
        self.gridLayout_3 = QGridLayout(self.sourceTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sourceDescription = QCheckBox(self.sourceTab)
        self.sourceDescription.setObjectName("sourceDescription")
        self.gridLayout.addWidget(self.sourceDescription, 0, 6, 1, 1)
        self.shotLabel = QLabel(self.sourceTab)
        self.shotLabel.setObjectName("shotLabel")
        self.gridLayout.addWidget(self.shotLabel, 0, 0, 1, 1)
        self.tracePattern = QLineEdit(self.sourceTab)
        self.tracePattern.setObjectName("tracePattern")
        self.gridLayout.addWidget(self.tracePattern, 0, 5, 1, 1)
        self.shotInput = QLineEdit(self.sourceTab)
        self.shotInput.setObjectName("shotInput")
        self.gridLayout.addWidget(self.shotInput, 0, 1, 1, 1)
        self.readDataButton = QPushButton(self.sourceTab)
        self.readDataButton.setObjectName("readDataButton")
        self.gridLayout.addWidget(self.readDataButton, 0, 2, 1, 1)
        self.traceLabel = QLabel(self.sourceTab)
        self.traceLabel.setObjectName("traceLabel")
        self.gridLayout.addWidget(self.traceLabel, 0, 4, 1, 1)
        self.lastShotButton = QPushButton(self.sourceTab)
        self.lastShotButton.setObjectName("lastShotButton")
        self.gridLayout.addWidget(self.lastShotButton, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.splitter = QSplitter(self.sourceTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeView = QTreeWidget(self.splitter)
        self.treeView.setColumnCount(1)
        self.treeView.setObjectName("treeView")
        self.treeView.headerItem().setText(0, "Source")
        self.treeView.header().setVisible(False)
        self.treeView.header().setDefaultSectionSize(200)
        self.treeView.header().setStretchLastSection(True)
        self.sourceTable = QTableWidget(self.splitter)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceTable.sizePolicy().hasHeightForWidth())
        self.sourceTable.setSizePolicy(sizePolicy)
        self.sourceTable.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.sourceTable.setAlternatingRowColors(True)
        self.sourceTable.setSelectionMode(QAbstractItemView.MultiSelection)
        self.sourceTable.setShowGrid(False)
        self.sourceTable.setColumnCount(1)
        self.sourceTable.setObjectName("sourceTable")
        self.sourceTable.setColumnCount(1)
        self.sourceTable.setRowCount(0)
        self.sourceTable.horizontalHeader().setVisible(False)
        self.sourceTable.horizontalHeader().setDefaultSectionSize(200)
        self.sourceTable.horizontalHeader().setStretchLastSection(False)
        self.sourceTable.verticalHeader().setVisible(False)
        self.sourceTable.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_3.addWidget(self.splitter, 1, 0, 1, 1)
        self.tabWidget.addTab(self.sourceTab, "")
        self.dataTab = QWidget()
        self.dataTab.setObjectName("dataTab")
        self.gridLayout_5 = QGridLayout(self.dataTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_2 = QSplitter(self.dataTab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.dataTable = QTableWidget(self.splitter_2)
        self.dataTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.dataTable.setAlternatingRowColors(True)
        self.dataTable.setSelectionMode(QAbstractItemView.MultiSelection)
        self.dataTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.dataTable.setShowGrid(False)
        self.dataTable.setGridStyle(QtCore.Qt.SolidLine)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(4)
        self.dataTable.setRowCount(0)
        item = QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.dataTable.verticalHeader().setDefaultSectionSize(20)
        self.textOutput = QTextEdit(self.splitter_2)
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName("textOutput")
        self.layoutWidget = QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.commandInput = ConsoleWidget(self.layoutWidget)
        self.commandInput.setObjectName("commandInput")
        self.gridLayout_4.addWidget(self.commandInput, 0, 1, 1, 1)
        self.commandButton = QPushButton(self.layoutWidget)
        self.commandButton.setObjectName("commandButton")
        self.gridLayout_4.addWidget(self.commandButton, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dataTab, "")
        self.plotTab = QWidget()
        self.plotTab.setObjectName("plotTab")
        self.tabWidget.addTab(self.plotTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdd_source = QMenu(self.menuFile)
        self.menuAdd_source.setObjectName("menuAdd_source")
        self.menuPlot = QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuCommand = QMenu(self.menubar)
        self.menuCommand.setObjectName("menuCommand")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoadState = QAction(MainWindow)
        self.actionLoadState.setObjectName("actionLoadState")
        self.actionSaveState = QAction(MainWindow)
        self.actionSaveState.setObjectName("actionSaveState")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionXPAD_tree = QAction(MainWindow)
        self.actionXPAD_tree.setObjectName("actionXPAD_tree")
        self.actionNetCDF_file = QAction(MainWindow)
        self.actionNetCDF_file.setObjectName("actionNetCDF_file")
        self.actionPlot = QAction(MainWindow)
        self.actionPlot.setObjectName("actionPlot")
        self.actionOPlot = QAction(MainWindow)
        self.actionOPlot.setObjectName("actionOPlot")
        self.actionMPlot = QAction(MainWindow)
        self.actionMPlot.setObjectName("actionMPlot")
        self.actionXYPlot = QAction(MainWindow)
        self.actionXYPlot.setObjectName("actionXYPlot")
        self.actionZPlot = QAction(MainWindow)
        self.actionZPlot.setObjectName("actionZPlot")
        self.actionBOUT_data = QAction(MainWindow)
        self.actionBOUT_data.setObjectName("actionBOUT_data")
        self.actionContour = QAction(MainWindow)
        self.actionContour.setObjectName("actionContour")
        self.actionContour_filled = QAction(MainWindow)
        self.actionContour_filled.setObjectName("actionContour_filled")
        self.actionClearFig = QAction(MainWindow)
        self.actionClearFig.setObjectName("actionClearFig")
        self.actionWrite_ASCII = QAction(MainWindow)
        self.actionWrite_ASCII.setObjectName("actionWrite_ASCII")
        self.actionAdd = QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionSubtract = QAction(MainWindow)
        self.actionSubtract.setObjectName("actionSubtract")
        self.actionMultiply = QAction(MainWindow)
        self.actionMultiply.setObjectName("actionMultiply")
        self.actionDivide = QAction(MainWindow)
        self.actionDivide.setObjectName("actionDivide")
        self.actionChop = QAction(MainWindow)
        self.actionChop.setObjectName("actionChop")
        self.actionIntegrate = QAction(MainWindow)
        self.actionIntegrate.setObjectName("actionIntegrate")
        self.actionDf_dt = QAction(MainWindow)
        self.actionDf_dt.setObjectName("actionDf_dt")
        self.actionSmooth = QAction(MainWindow)
        self.actionSmooth.setObjectName("actionSmooth")
        self.actionLow_pass_filter = QAction(MainWindow)
        self.actionLow_pass_filter.setObjectName("actionLow_pass_filter")
        self.actionHigh_pass_filter = QAction(MainWindow)
        self.actionHigh_pass_filter.setObjectName("actionHigh_pass_filter")
        self.actionBand_pass_filter = QAction(MainWindow)
        self.actionBand_pass_filter.setObjectName("actionBand_pass_filter")
        self.actionFFTP = QAction(MainWindow)
        self.actionFFTP.setObjectName("actionFFTP")
        self.actionRunFFT = QAction(MainWindow)
        self.actionRunFFT.setObjectName("actionRunFFT")
        self.actionReciprocal = QAction(MainWindow)
        self.actionReciprocal.setObjectName("actionReciprocal")
        self.actionExponential = QAction(MainWindow)
        self.actionExponential.setObjectName("actionExponential")
        self.actionAbsolute = QAction(MainWindow)
        self.actionAbsolute.setObjectName("actionAbsolute")
        self.actionArctan = QAction(MainWindow)
        self.actionArctan.setObjectName("actionArctan")
        self.actionNlog = QAction(MainWindow)
        self.actionNlog.setObjectName("actionNlog")
        self.actionNorm = QAction(MainWindow)
        self.actionNorm.setObjectName("actionNorm")
        self.actionInvert = QAction(MainWindow)
        self.actionInvert.setObjectName("actionInvert")
        self.actionAddCon = QAction(MainWindow)
        self.actionAddCon.setObjectName("actionAddCon")
        self.actionSubCon = QAction(MainWindow)
        self.actionSubCon.setObjectName("actionSubCon")
        self.actionMulCon = QAction(MainWindow)
        self.actionMulCon.setObjectName("actionMulCon")
        self.actionDivCon = QAction(MainWindow)
        self.actionDivCon.setObjectName("actionDivCon")
        self.actionPowCon = QAction(MainWindow)
        self.actionPowCon.setObjectName("actionPowCon")
        self.actionChangeName = QAction(MainWindow)
        self.actionChangeName.setObjectName("actionChangeName")
        self.actionChangeUnits = QAction(MainWindow)
        self.actionChangeUnits.setObjectName("actionChangeUnits")
        self.actionClip = QAction(MainWindow)
        self.actionClip.setObjectName("actionClip")
        self.actionStats = QAction(MainWindow)
        self.actionStats.setObjectName("actionStats")
        self.actionTimeOff = QAction(MainWindow)
        self.actionTimeOff.setObjectName("actionTimeOff")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDeleteTrace = QAction(MainWindow)
        self.actionDeleteTrace.setObjectName("actionDeleteTrace")
        self.menuAdd_source.addAction(self.actionNetCDF_file)
        self.menuAdd_source.addAction(self.actionXPAD_tree)
        self.menuAdd_source.addAction(self.actionBOUT_data)
        self.menuFile.addAction(self.menuAdd_source.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoadState)
        self.menuFile.addAction(self.actionSaveState)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionWrite_ASCII)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPlot.addAction(self.actionPlot)
        self.menuPlot.addAction(self.actionOPlot)
        self.menuPlot.addAction(self.actionMPlot)
        self.menuPlot.addAction(self.actionZPlot)
        self.menuPlot.addAction(self.actionXYPlot)
        self.menuPlot.addAction(self.actionContour)
        self.menuPlot.addAction(self.actionContour_filled)
        self.menuPlot.addAction(self.actionClearFig)
        self.menuCommand.addAction(self.actionDeleteTrace)
        self.menuCommand.addSeparator()
        self.menuCommand.addAction(self.actionChop)
        self.menuCommand.addSeparator()
        self.menuCommand.addAction(self.actionIntegrate)
        self.menuCommand.addAction(self.actionDf_dt)
        self.menuCommand.addAction(self.actionSmooth)
        self.menuCommand.addAction(self.actionBand_pass_filter)
        self.menuCommand.addSeparator()
        self.menuCommand.addAction(self.actionAdd)
        self.menuCommand.addAction(self.actionSubtract)
        self.menuCommand.addAction(self.actionMultiply)
        self.menuCommand.addAction(self.actionDivide)
        self.menuCommand.addSeparator()
        self.menuCommand.addAction(self.actionFFTP)
        self.menuCommand.addAction(self.actionRunFFT)
        self.menuCommand.addSeparator()
        self.menuCommand.addAction(self.actionReciprocal)
        self.menuCommand.addAction(self.actionExponential)
        self.menuCommand.addAction(self.actionAbsolute)
        self.menuCommand.addAction(self.actionArctan)
        self.menuCommand.addAction(self.actionNlog)
        self.menuCommand.addAction(self.actionNorm)
        self.menuCommand.addAction(self.actionInvert)
        self.menuCommand.addAction(self.actionAddCon)
        self.menuCommand.addAction(self.actionSubCon)
        self.menuCommand.addAction(self.actionMulCon)
        self.menuCommand.addAction(self.actionDivCon)
        self.menuCommand.addAction(self.actionPowCon)
        self.menuCommand.addAction(self.actionChangeName)
        self.menuCommand.addAction(self.actionChangeUnits)
        self.menuCommand.addAction(self.actionClip)
        self.menuCommand.addAction(self.actionStats)
        self.menuCommand.addAction(self.actionTimeOff)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuCommand.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QApplication.translate("MainWindow", "PyXPad", None, UnicodeUTF8))
        self.sourceDescription.setText(QApplication.translate("MainWindow", "Description", None, UnicodeUTF8))
        self.shotLabel.setText(QApplication.translate("MainWindow", "Shot:", None, UnicodeUTF8))
        self.readDataButton.setText(QApplication.translate("MainWindow", "&Read", None, UnicodeUTF8))
        self.traceLabel.setText(QApplication.translate("MainWindow", "Trace:", None, UnicodeUTF8))
        self.lastShotButton.setToolTip(QApplication.translate("MainWindow", "Get last shot number", None, UnicodeUTF8))
        self.lastShotButton.setText(QApplication.translate("MainWindow", "&Last shot", None, UnicodeUTF8))
        self.sourceTable.setToolTip(QApplication.translate("MainWindow", "List of available signals", None, UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sourceTab), QApplication.translate("MainWindow", "&Sources", None, UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(0).setText(QApplication.translate("MainWindow", "Name", None, UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(1).setText(QApplication.translate("MainWindow", "Source", None, UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(2).setText(QApplication.translate("MainWindow", "Trace", None, UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(3).setText(QApplication.translate("MainWindow", "Comments", None, UnicodeUTF8))
        self.label_3.setText(QApplication.translate("MainWindow", "Command:", None, UnicodeUTF8))
        self.commandButton.setText(QApplication.translate("MainWindow", "Run", None, UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), QApplication.translate("MainWindow", "&Data", None, UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), QApplication.translate("MainWindow", "&Plot", None, UnicodeUTF8))
        self.menuFile.setTitle(QApplication.translate("MainWindow", "&File", None, UnicodeUTF8))
        self.menuAdd_source.setTitle(QApplication.translate("MainWindow", "&Add source", None, UnicodeUTF8))
        self.menuPlot.setTitle(QApplication.translate("MainWindow", "&Graphics", None, UnicodeUTF8))
        self.menuCommand.setTitle(QApplication.translate("MainWindow", "&Command", None, UnicodeUTF8))
        self.menuHelp.setTitle(QApplication.translate("MainWindow", "&Help", None, UnicodeUTF8))
        self.actionLoadState.setText(QApplication.translate("MainWindow", "&Load state", None, UnicodeUTF8))
        self.actionSaveState.setText(QApplication.translate("MainWindow", "&Save state", None, UnicodeUTF8))
        self.actionExit.setText(QApplication.translate("MainWindow", "E&xit", None, UnicodeUTF8))
        self.actionExit.setToolTip(QApplication.translate("MainWindow", "Exit pyXpad", None, UnicodeUTF8))
        self.actionExit.setShortcut(QApplication.translate("MainWindow", "Ctrl+Q", None, UnicodeUTF8))
        self.actionXPAD_tree.setText(QApplication.translate("MainWindow", "XPAD tree", None, UnicodeUTF8))
        self.actionXPAD_tree.setToolTip(QApplication.translate("MainWindow", "Load a tree of XPAD items", None, UnicodeUTF8))
        self.actionNetCDF_file.setText(QApplication.translate("MainWindow", "NetCDF file", None, UnicodeUTF8))
        self.actionPlot.setText(QApplication.translate("MainWindow", "&Plot", None, UnicodeUTF8))
        self.actionOPlot.setText(QApplication.translate("MainWindow", "&OPlot", None, UnicodeUTF8))
        self.actionMPlot.setText(QApplication.translate("MainWindow", "&MPlot", None, UnicodeUTF8))
        self.actionXYPlot.setText(QApplication.translate("MainWindow", "&XYPlot", None, UnicodeUTF8))
        self.actionZPlot.setText(QApplication.translate("MainWindow", "&ZPlot", None, UnicodeUTF8))
        self.actionBOUT_data.setText(QApplication.translate("MainWindow", "BOUT++ data", None, UnicodeUTF8))
        self.actionBOUT_data.setToolTip(QApplication.translate("MainWindow", "Read BOUT++ data directory", None, UnicodeUTF8))
        self.actionBOUT_data.setShortcut(QApplication.translate("MainWindow", "Ctrl+S", None, UnicodeUTF8))
        self.actionContour.setText(QApplication.translate("MainWindow", "&Contour", None, UnicodeUTF8))
        self.actionContour_filled.setText(QApplication.translate("MainWindow", "Contour &filled", None, UnicodeUTF8))
        self.actionClearFig.setText(QApplication.translate("MainWindow", "C&lear Figure", None, UnicodeUTF8))
        self.actionWrite_ASCII.setText(QApplication.translate("MainWindow", "&Write ASCII", None, UnicodeUTF8))
        self.actionAdd.setText(QApplication.translate("MainWindow", "X+Y (Sum Channels)", None, UnicodeUTF8))
        self.actionSubtract.setText(QApplication.translate("MainWindow", "X-Y", None, UnicodeUTF8))
        self.actionMultiply.setText(QApplication.translate("MainWindow", "X*Y", None, UnicodeUTF8))
        self.actionDivide.setText(QApplication.translate("MainWindow", "X/Y", None, UnicodeUTF8))
        self.actionChop.setText(QApplication.translate("MainWindow", "Chop", None, UnicodeUTF8))
        self.actionIntegrate.setText(QApplication.translate("MainWindow", "Integrate", None, UnicodeUTF8))
        self.actionDf_dt.setText(QApplication.translate("MainWindow", "df/dt", None, UnicodeUTF8))
        self.actionSmooth.setText(QApplication.translate("MainWindow", "Smooth", None, UnicodeUTF8))
        self.actionLow_pass_filter.setText(QApplication.translate("MainWindow", "Low pass filter", None, UnicodeUTF8))
        self.actionHigh_pass_filter.setText(QApplication.translate("MainWindow", "High pass filter", None, UnicodeUTF8))
        self.actionBand_pass_filter.setText(QApplication.translate("MainWindow", "Band pass filter", None, UnicodeUTF8))
        self.actionFFTP.setText(QApplication.translate("MainWindow", "FFTP", None, UnicodeUTF8))
        self.actionRunFFT.setText(QApplication.translate("MainWindow", "Running FFT", None, UnicodeUTF8))
        self.actionReciprocal.setText(QApplication.translate("MainWindow", "1/X", None, UnicodeUTF8))
        self.actionExponential.setText(QApplication.translate("MainWindow", "exp", None, UnicodeUTF8))
        self.actionAbsolute.setText(QApplication.translate("MainWindow", "abs", None, UnicodeUTF8))
        self.actionArctan.setText(QApplication.translate("MainWindow", "arctan", None, UnicodeUTF8))
        self.actionNlog.setText(QApplication.translate("MainWindow", "ln", None, UnicodeUTF8))
        self.actionNorm.setText(QApplication.translate("MainWindow", "Normalise", None, UnicodeUTF8))
        self.actionInvert.setText(QApplication.translate("MainWindow", "Invert", None, UnicodeUTF8))
        self.actionAddCon.setText(QApplication.translate("MainWindow", "X+C", None, UnicodeUTF8))
        self.actionSubCon.setText(QApplication.translate("MainWindow", "X-C", None, UnicodeUTF8))
        self.actionMulCon.setText(QApplication.translate("MainWindow", "X*C", None, UnicodeUTF8))
        self.actionDivCon.setText(QApplication.translate("MainWindow", "X/C", None, UnicodeUTF8))
        self.actionPowCon.setText(QApplication.translate("MainWindow", "X^C", None, UnicodeUTF8))
        self.actionChangeName.setText(QApplication.translate("MainWindow", "Change Name", None, UnicodeUTF8))
        self.actionChangeUnits.setText(QApplication.translate("MainWindow", "Change Units", None, UnicodeUTF8))
        self.actionClip.setText(QApplication.translate("MainWindow", "Clip", None, UnicodeUTF8))
        self.actionStats.setText(QApplication.translate("MainWindow", "Statistics", None, UnicodeUTF8))
        self.actionTimeOff.setText(QApplication.translate("MainWindow", "Time Offset", None, UnicodeUTF8))
        self.actionAbout.setText(QApplication.translate("MainWindow", "&About", None, UnicodeUTF8))
        self.actionDeleteTrace.setText(QApplication.translate("MainWindow", "&Delete Trace", None, UnicodeUTF8))

from .console_widget import ConsoleWidget
